version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      day: sunday
      interval: weekly
    groups:
      npm-security:
        applies-to: security-updates
        patterns: ['*']
      npm-update:
        applies-to: version-updates
        patterns: ['*']
